import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Random;

public class Writer implements Runnable {
    private Frame frame;
    private boolean isRunning;

    public Writer(Frame frame) {
        this.frame = frame;
        this.isRunning = true;
        frame.getButton().addActionListener(e -> stopWriting());
    }

    public void run() {
        frame.setVisible(true);
        String nl = System.lineSeparator();
        Random rand = new Random();
        float r = rand.nextFloat();
        float g = rand.nextFloat();
        float b = rand.nextFloat();
        Color randomColor = new Color(r, g, b);
        Font font;
        frame.getTextArea().append("This text is generated by a loop and will keep " +
                "appearing until you press stop!" + nl);
        while (isRunning) {
            r = rand.nextFloat();
            g = rand.nextFloat();
            b = rand.nextFloat();
            randomColor = new Color(r, g, b);
            frame.getTextArea().setForeground(randomColor);
            font = new Font("Serif", Font.BOLD, rand.nextInt(50) + 1);
            frame.getTextArea().setFont(font);
            frame.getTextArea().append("");
            try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    private void stopWriting() {
        this.isRunning = false;
    }
}
